[server]
node_id = 1
node_address= "node1:9000"
community_string="test"
binding_addr="0.0.0.0:3000"

[[peers]]
node_id = 2
node_address = "node2:9000"

[[logs]]
path = "node0_0"
lid = "3d30aa56-98b2-4891-aec5-847cee6e1703"

[[logs]]
path ="node0_1"
lid ="2275a90d-5884-4498-9ba5-91122e2fe875"
