version: '3'
services:
        node1:
                build: .
                environment: 
                        RUST_BACKTRACE: 1
                        RUST_LOG: raft=debug
                volumes: 
                        - ./config:/config
                        - ./data:/data
                networks:
                        - cluster 
                ports:
                        - "9000:9000"
                        - "3000:3000"
        node2:
                build: .
                environment: 
                        RUST_BACKTRACE: 1
                        RUST_LOG: raft=debug
                volumes: 
                        - ./config2:/config
                        - ./data2:/data
                networks:
                        - cluster 
                ports:
                        - "9001:9000"
                        - "3001:3000"
networks:
        cluster: 
                driver: bridge
